name: wallet_value
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    http: ^0.13.4
    url_strategy: ^0.2.0
    google_fonts: ^3.0.0
    firebase_core: ^1.17.0
    firebase_analytics: ^9.1.8
    ethereum_addresses: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
