// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtONZUm4ghIk8Qo2XsA0st6a41fo2_J4c',
    appId: '1:732096660902:web:718fec1161c04a683cbb67',
    messagingSenderId: '732096660902',
    projectId: 'os-value',
    authDomain: 'os-value.firebaseapp.com',
    storageBucket: 'os-value.appspot.com',
    measurementId: 'G-M2RZNEGPNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMRNe_cPp__SxMnMdTIEmo7CYmaV17ehc',
    appId: '1:732096660902:android:fa79b47cc99d5efd3cbb67',
    messagingSenderId: '732096660902',
    projectId: 'os-value',
    storageBucket: 'os-value.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPxwgwmHxzDeHXVjKzHAjRV5LX90jP5k',
    appId: '1:732096660902:ios:80cc77dee70b45233cbb67',
    messagingSenderId: '732096660902',
    projectId: 'os-value',
    storageBucket: 'os-value.appspot.com',
    iosClientId: '732096660902-5v8si7noubgf55vd2dn462h0h03bfbiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletValue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPxwgwmHxzDeHXVjKzHAjRV5LX90jP5k',
    appId: '1:732096660902:ios:80cc77dee70b45233cbb67',
    messagingSenderId: '732096660902',
    projectId: 'os-value',
    storageBucket: 'os-value.appspot.com',
    iosClientId: '732096660902-5v8si7noubgf55vd2dn462h0h03bfbiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.walletValue',
  );
}
